[build]
  command = "npm run build"
  functions = "build/server"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
